language: rust
cache: cargo
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
notifications:
  email: false
script:
  - cargo build --verbose
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
